# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MAB Ecosystem
author: MAB Robotics
logo: logo.png

# Execution settings
# https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the LaTeX output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/mabrobotics/MD80-x-CANdle-Documentation  # Online location of your book
  branch: devel  # Which branch of the repository should be used when creating links

# HTML-specific settings
# https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  comments:
    hypothesis: true
  favicon: logo32x32.png

sphinx:
  config:
    html_context:
      default_mode: light
    # âœ… Recommended addition for math rendering:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_extra_path: "./candlelib/includes"

myst:
  enable_extensions:
    - colon_fence
    - attrs_inline
    - attrs_block
    - dollarmath
    - amsmath

exclude_patterns:
  - venv/*
  - .venv/*
  # - _build/*
  - Thumbs.db
  - .DS_Store
